### ISSUE TITLE
Can you share how you finetune it on ATCO2 dataset?

### ISSUE THREAD

**Issue by Larry-Ye** [jlvdoorn/WhisperATC#3]
Can you share how you finetune Whisper?

**Comment by jlvdoorn** [comment]
If you need any background on the research, please read this [paper](http://resolver.tudelft.nl/uuid:8aa780bf-47b6-4f81-b112-29e23bc06a7d). The complete code is published in the [fine-tuning](https://github.com/jlvdoorn/WhisperATC/tree/main/Fine-Tune) folder of this repo. 

Does that help you out?

**Comment by Larry-Ye** [comment]
I can not prepare the dataset at the beginning.
When I run CreateDataset/01-Prepare.py, it report error.
![image](https://github.com/jlvdoorn/WhisperATC/assets/71308801/f65775a8-b494-45c0-a90f-7b6d573cbb96)
I don't know how to fix it. I try a lot of times. Maybe there are some logic error when it load the dataset.
It might because the program read a xml files without any head or context. So the program said the variable is not defined. I wonder if you can fix it.

**Comment by jlvdoorn** [comment]
It cannot find the correct '.info' files. You should double check your working directory and relative paths. 
Hope that helps.
