### ISSUE TITLE
Fine tuned models are not available

### ISSUE THREAD

**Issue by sfo** [jlvdoorn/WhisperATC#4]
Hi! I found your very interesting paper on this year's ICRAT conference program. Unfortunately, I could not attend the talk, since I had an own one in a parallel track.

After reading the paper, I tried and played around with your code and the models (see my fork at https://github.com/sfo/WhisperATC, if interested).
However, the fine tuned models could not be obtained from Hugging Face and model loading fails:
```
Traceback (most recent call last):
  File "/home/service/WhisperATC/Evaluate/Evaluate-FineTuned_transcribe.py", line 66, in <module>
    hf_state_dict = torch.load('./'+mdl.split('/')[-1]+'/pytorch_model.bin')    # pytorch_model.bin file
  File "/home/service/.miniforge3/envs/whisper/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/service/.miniforge3/envs/whisper/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/service/.miniforge3/envs/whisper/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './whisper-large-v3-atco2-asr/pytorch_model.bin'
```
Checking the repositories online (e.g. https://huggingface.co/jlvdoorn/whisper-large-v3-atco2-asr/tree/main), there is indeed no `pytorch_model.bin` file available.

Could you submit those files or point me to the correct location?

**Comment by jlvdoorn** [comment]
Hi there, 

Thank you for your interest! And sorry for the late reply. 

I see you are trying to load the 'new versions' (e.g., v3). This only comes in the 'model.safetensors' variant instead of the older 'pytorch_model.bin' variant. 

More info [here](https://huggingface.co/docs/diffusers/v0.13.0/en/using-diffusers/using_safetensors#what-is-safetensors).
